branches:
  only:
  - master

sudo: required

services:
  - docker

script:
  - docker container run --rm -it -v $(pwd):/src jojomi/hugo hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: public
  repo: ansible-br/ansible-br.github.io
  on:
    branch: master
